#Listar coordenadores
PATCH  http://localhost:3000/atualizar/25
{
 "nome":"teste editado",   
 "email":"teste@gmail.com",
 "matricula":"2986"
 
}
###
get http://localhost:3000/coordenador/listar
Content-Type: application/json

###

post http://localhost:3000/coordenador/login
Content-Type: application/json
{
 "email":"paulo@gmail.com",
 "senha":"123456"
}

###
GET http://localhost:3000/curso/listar
Content-Type: application/json

###
get http://localhost:3000/docente/listar
Content-Type: application/json
###
get http://localhost:3000/docente/localizar/4

###
get http://localhost:3000/curso/listar
###
post  http://localhost:3000/docente/cadastrar
Content-Type: application/json
{
    "nome":"mestre",
    "matricula":"33333",
    "id_curso": 6,
    "dias":"segunda-terça-quarta"
}